---
abstract: 'Signs/verifies Internet mail with DKIM/DomainKey signatures'
author:
  - 'Marc Bradshaw <marc@marcbradshaw.net>'
build_requires:
  Data::Dumper: '0'
  Net::DNS::Resolver: '0'
  Net::DNS::Resolver::Mock: '0'
  Test::More: '0'
  Test::RequiresInternet: '0'
  Test::Simple: '0'
  YAML::XS: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.014, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mail-DKIM
requires:
  Carp: '0'
  Crypt::OpenSSL::RSA: '0'
  Digest::SHA: '0'
  MIME::Base64: '0'
  Mail::Address: '0'
  Mail::AuthenticationResults::Header::AuthServID: '0'
  Mail::AuthenticationResults::Parser: '0'
  Net::DNS: '0'
  base: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/fastmail/mail-dkim/issues
  repository: git://github.com/fastmail/mail-dkim.git
version: '1.20200907'
x_contributors:
  - 'Aaron Thompson <dev@aaront.org>'
  - 'Bron Gondwana <brong@fastmail.fm>'
  - 'Christian Jaeger <ch@christianjaeger.ch>'
  - 'Damien MASCRÉ <damienmascre@free.fr>'
  - 'jasonlong <jasonlong@f38efd27-133c-0410-a3cc-a5f95e9cf04f>'
  - 'José Borges Ferreira <jose.ferreira@bitsighttech.com>'
  - 'Martijn van de Streek <martijn@vandestreek.net>'
  - 'Martin H. Sluka <martin@sluka.de>'
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
x_generated_by_perl: v5.30.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
